apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  labels:
    app: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
      - name: postgres-exporter
        image: quay.io/prometheuscommunity/postgres-exporter
        resources:
          requests:
            cpu: '0.1'
            memory: 64Mi
          limits:
            cpu: '0.1'
            memory: 64Mi
        ports:
          - containerPort: 9187
            hostPort: 9187
        env:
          - name: PG_EXPORTER_EXCLUDE_DATABASES
            value: template0,template1
          - name: DATA_SOURCE_URI
            value: postgres-0.pg:5432/postgres?sslmode=disable
          - name: DATA_SOURCE_USER
            valueFrom:
              secretKeyRef:
                name: pg-pass
                key: POSTGRES_USER
          - name: DATA_SOURCE_PASS
            valueFrom:
              secretKeyRef:
                name: pg-pass
                key: POSTGRES_PASSWORD