apiVersion: v1
kind: Service
metadata:
  name: pg
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - name: main
      port: 5432
    - port: 9187
      name: metrics
--- 
apiVersion: v1
kind: Service
metadata:
  name: pg-nodeport
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432