apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow

images:
  - name: ghcr.io/dnbnero/airflow
    newName: ghcr.io/dnbnero/airflow
    newTag: main

resources:
  - ./base/namespace.yaml
  - ./base/apiserver.yaml
  - ./base/dag-processor.yaml
  - ./base/scheduler.yaml
  - ./base/triggerer.yaml
  - ./base/worker.yaml
  - ./base/valkey.yaml

configMapGenerator:
  - name: airflow-cfg
    files:
      - ./configs/airflow.cfg

secretGenerator:
  - name: airflow-secrets
    envs:
      - ./configs/.env
      
labels:
  - pairs:
      managed-by-kustomize: "true"