apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs-filer
spec:
  selector:
    matchLabels:
      app: seaweedfs-filer
  replicas: 1
  template:
    metadata:
      labels:
        app: seaweedfs-filer
    spec:
      containers:
        - name: seaweedfs-filer
          image: docker.io/chrislusf/seaweedfs
          envFrom:
          - secretRef:
              name: filer-pg
          ports:
            - containerPort: 9326
          args:
            - filer
            - -master=seaweedfs-master:9333
            - -ip.bind=0.0.0.0
            - -metricsPort=9326
            - -port=8888
            - -s3.port=8333
      volumes:
        - name: filer-pg
          projected:
            sources:
              - secret:
                  name: filer-pg
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-filer
spec:
  clusterIP: None
  selector:
    app: seaweedfs-filer
  ports:
  - port: 8888
    name: filer
  - port: 18888
    name: filer-grpc
  - port: 9326
    name: metrics