apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-path-provisioner

configMapGenerator:
  - name: local-path-config
    files:
      - ./configs/config.json
      - ./configs/helperPod.yaml
      - ./configs/setup
      - ./configs/teardown
    options:
      disableNameSuffixHash: true


resources:
  - ./base/deployment.yaml
  - ./base/namespace.yaml
  - ./base/rbac.yaml
  - ./base/storageclass.yaml