apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  - ./base/deployment.yaml
  - ./base/namespace.yaml
  - ./base/service.yaml

configMapGenerator:
  - name: datasources
    files:
      - ./configs/datasources/prometheus-datasource.yml
      - ./configs/datasources/victoriametrics-datasource.yml

secretGenerator:
  - name: secret
    envs:
      - ./configs/.env
      
labels:
  - pairs:
      managed-by-kustomize: "true"