{
 "title": "SeaweedFS",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Filer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Filer Request Duration 90th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(SeaweedFS_filerStore_request_seconds_bucket[1m])) by (le))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(SeaweedFS_filerStore_request_seconds_bucket[1m])) by (le, type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Filer Request Duration 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(SeaweedFS_filerStore_request_seconds_bucket[1m])) by (le))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(SeaweedFS_filerStore_request_seconds_bucket[1m])) by (le, type))",
     "legendFormat": "{{type}}"
    },
    {}
   ]
  },
  {
   "title": "Filer Request Duration 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_filerStore_request_seconds_bucket[1m])) by (le))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_filerStore_request_seconds_bucket[1m])) by (le, type))",
     "legendFormat": "{{type}}"
    },
    {}
   ]
  },
  {
   "title": "Filer QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(SeaweedFS_filerStore_request_total[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "S3 Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "S3 Request Duration 90th percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(SeaweedFS_s3_request_seconds_bucket[1m])) by (le))",
       "legendFormat": "average"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(SeaweedFS_s3_request_seconds_bucket[1m])) by (le, type, bucket))",
       "legendFormat": "{{bucket}} {{type}}"
      }
     ]
    },
    {
     "title": "S3 Request Duration 95th percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(SeaweedFS_s3_request_seconds_bucket[1m])) by (le))",
       "legendFormat": "average"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(SeaweedFS_s3_request_seconds_bucket[1m])) by (le, type, bucket))",
       "legendFormat": "{{bucket}} {{type}}"
      }
     ]
    },
    {
     "title": "S3 Request Duration 99th percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_s3_request_seconds_bucket[1m])) by (le))",
       "legendFormat": "average"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_s3_request_seconds_bucket[1m])) by (le, type, bucket))",
       "legendFormat": "{{bucket}} {{type}}"
      }
     ]
    },
    {
     "title": "S3 Bucket Traffic Received",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(SeaweedFS_s3_bucket_traffic_received_bytes_total[$__interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "S3 Bucket Traffic Sent",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(SeaweedFS_s3_bucket_traffic_sent_bytes_total[$__interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "S3 API QPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(SeaweedFS_s3_request_total[1m])",
       "legendFormat": "{{bucket}} {{type}}"
      }
     ]
    },
    {
     "title": "S3 API Monthly Cost if on AWS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum by (type) (increase(SeaweedFS_s3_request_total{type=~'PUT|COPY|POST|LIST'}[$__range]))*0.000005",
       "legendFormat": "{{type}} requests"
      },
      {
       "expr": "sum(increase(SeaweedFS_s3_request_total{type=~'PUT|COPY|POST|LIST'}[$__range]))*0.000005",
       "legendFormat": "All PUT, COPY, POST, LIST"
      },
      {
       "expr": "sum (increase(SeaweedFS_s3_request_total{type!~'PUT|COPY|POST|LIST'}[$__range]))*0.0000004",
       "legendFormat": "GET and all other"
      },
      {
       "expr": "sum by (type) (increase(SeaweedFS_s3_request_total{type!~'PUT|COPY|POST|LIST'}[$__range]))*0.0000004",
       "legendFormat": "{{type}} requests"
      }
     ]
    }
   ]
  },
  { "title": "Volume Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Volume Server Request Duration 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_volumeServer_request_seconds_bucket[1m])) by (le, exported_instance))",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_volumeServer_request_seconds_bucket[1m])) by (le))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Volume Server QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(SeaweedFS_volumeServer_request_total[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Volume Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(SeaweedFS_volumeServer_volumes) by (collection, type)",
     "legendFormat": "{{collection}} {{type}}"
    },
    {
     "expr": "sum(SeaweedFS_volumeServer_max_volumes)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Used Disk Space by Collection and Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(SeaweedFS_volumeServer_total_disk_size) by (collection, type)",
     "legendFormat": "{{collection}} {{type}}"
    },
    {
     "expr": "sum(SeaweedFS_volumeServer_total_disk_size)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Used Disk Space by Host",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(SeaweedFS_volumeServer_total_disk_size) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  { "title": "Filer Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Filer Store Request Duration 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_filerStore_request_seconds_bucket[1m])) by (le, type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Filer Store QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(SeaweedFS_filerStore_request_total [1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Filer Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Filer Go Memory Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{exported_job=\"filer\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{exported_job=\"filer\"}[30s])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{exported_job=\"filer\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{exported_job=\"filer\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Filer Go GC duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{exported_job=\"filer\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Filer Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "go_goroutines{exported_job=\"filer\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Process memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{exported_job=\"filer\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "resident {{exported_instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "process_virtual_memory_bytes{exported_job=\"filer\"}",
     "legendFormat": "virtual {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Open File Descriptor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
   "targets": [
    {
     "expr": "process_open_fds{exported_job=\"filer\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{exported_instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "process_max_fds{exported_job=\"filer\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{exported_instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}