{
 "title": "StarRocks / Shared Data",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "query": {
     "query": "label_values(up{job=\"starrocks\"},job)"
    }
   },
   {
    "name": "fe_master",
    "query": {
     "query": "query_result(node_info{group=\"fe\", job=\"$cluster_name\", type=\"is_master\"})"
    }
   },
   {
    "name": "fe_instance",
    "query": {
     "query": "up{group=\"fe\", job=\"$cluster_name\"}"
    }
   },
   {
    "name": "be_instance",
    "query": {
     "query": "up{group=\"be\", job=\"$cluster_name\"}"
    }
   },
   { "name": "interval", "query": "1m,2m,5m,10m" }
  ]
 },
 "panels": [
  { "title": "Publish Version", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency / QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "lake_publish_tablet_version_latency{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} avg"
    },
    {
     "expr": "lake_publish_tablet_version_latency_99{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} p99"
    },
    {
     "expr": "lake_publish_tablet_version_qps{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} qps"
    }
   ]
  },
  {
   "title": "Queued Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lake_publish_version_queued_tasks{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Metadata", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Get Tablet Metadata",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "lake_get_tablet_metadata_latency{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} avg"
    },
    {
     "expr": "lake_get_tablet_metadata_latency_99{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} p99"
    },
    {
     "expr": "lake_get_tablet_metadata_qps{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} qps"
    }
   ]
  },
  {
   "title": "Put Tablet Metadata",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "lake_put_tablet_metadata_latency{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} avg"
    },
    {
     "expr": "lake_put_tablet_metadata_latency_99{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} p99"
    },
    {
     "expr": "lake_put_tablet_metadata_qps{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} qps"
    }
   ]
  },
  {
   "title": "Get Txn Log",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "lake_get_txn_log_latency{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} avg"
    },
    {
     "expr": "lake_get_txn_log_latency_99{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} p99"
    },
    {
     "expr": "lake_get_txn_log_qps{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} qps"
    }
   ]
  },
  {
   "title": "Put Txn Log",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "lake_put_txn_log_latency{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} avg"
    },
    {
     "expr": "lake_put_txn_log_latency_99{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} p99"
    },
    {
     "expr": "lake_put_txn_log_qps{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} qps"
    }
   ]
  },
  { "title": "Metacache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Metacache Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "lake_metacache_usage{job=\"$cluster_name\"} / lake_metacache_capacity{job=\"$cluster_name\"} * 100",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Delvec Cache Miss Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lake_delvec_cache_miss_minute{job=\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Metadata Cache Miss Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lake_metadata_cache_miss_minute"
    }
   ]
  },
  {
   "title": "Txn Log Cache Miss Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "lake_txn_log_cache_miss_minute{job=\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Segment Cache Miss Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "lake_segment_cache_miss_minute{job=\"$cluster_name\"}"
    }
   ]
  },
  { "title": "Vacuum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Vacuum Deletes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "lake_vacuum_del_file_latency{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} avg"
    },
    {
     "expr": "lake_vacuum_del_file_latency_99{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} p99"
    },
    {
     "expr": "lake_vacuum_del_file_qps{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} qps"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "lake_vacuum_del_file_fails{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} fails"
    }
   ]
  },
  { "title": "Loading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "starrocks_be_async_delta_writer_queue_count{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} async_delta_writer_qsize"
    },
    {
     "expr": "starrocks_be_memtable_flush_queue_count{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} memtable_flush_qsize"
    },
    {
     "expr": "starrocks_be_segment_flush_queue_count{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} segment_flush_qsize"
    },
    {
     "expr": "starrocks_be_update_apply_queue_count{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} update_apply_qsize"
    }
   ]
  }
 ]
}