apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: victoria

images:
  - name: docker.io/victoriametrics/victoria-logs
    newName: docker.io/victoriametrics/victoria-logs
    newTag: v1.23.3-victorialogs
  - name: docker.io/victoriametrics/victoria-metrics
    newName: docker.io/victoriametrics/victoria-metrics
    newTag: v1.119.0

resources:
  - ./base/victorialogs.yaml
  - ./base/victoriametrics.yaml
  - ./base/namespace.yaml
  - ./base/service.yaml
  - ./base/rbac.yaml
  - ./base/serviceaccount.yaml

configMapGenerator:
  - name: prometheus
    files:
      - ./configs/prometheus.yml

labels:
  - pairs:
      managed-by-kustomize: "true"