apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-qlc
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  nodePath: /var/lib/local-path-provisioner
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-mlc
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  nodePath: /var/mnt/data/local-path-provisioner